/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutsUserIdWorkoutIdRouteImport } from './routes/workouts/$userId.$workoutId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsUserIdWorkoutIdRoute = WorkoutsUserIdWorkoutIdRouteImport.update({
  id: '/workouts/$userId/$workoutId',
  path: '/workouts/$userId/$workoutId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workouts/$userId/$workoutId': typeof WorkoutsUserIdWorkoutIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workouts/$userId/$workoutId': typeof WorkoutsUserIdWorkoutIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workouts/$userId/$workoutId': typeof WorkoutsUserIdWorkoutIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/workouts/$userId/$workoutId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/workouts/$userId/$workoutId'
  id: '__root__' | '/' | '/workouts/$userId/$workoutId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkoutsUserIdWorkoutIdRoute: typeof WorkoutsUserIdWorkoutIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/$userId/$workoutId': {
      id: '/workouts/$userId/$workoutId'
      path: '/workouts/$userId/$workoutId'
      fullPath: '/workouts/$userId/$workoutId'
      preLoaderRoute: typeof WorkoutsUserIdWorkoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkoutsUserIdWorkoutIdRoute: WorkoutsUserIdWorkoutIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
